### ISSUE TITLE
Super interested in your project

### ISSUE THREAD

**Issue by softmarshmallow** [gorango/glyphs#11]
Sorry to open as an issue, but i couldn't find any contact info on your github. I'de like to contribute or maybe collaborate with my project `bridged.xyz` https://github.com/bridgedxyz . If you are interested please contact me via email on my profile.

Great work gorango!

I see a great great potential here.

**Comment by gorango** [comment]
Thanks for your interest and for reaching out! I really like what you're doing with bridged.

Apologies for the delay and lack of contact info - this project and my open source adventures are fledgeling.

I just reached out via email.
