### ISSUE TITLE
[docs] Search Mechanism

### ISSUE THREAD

**Issue by hasanaydins** [gorango/glyphs#33]
Please change search mechanism it works so bad. Use alike Algolia etc. 
Ex. when I type buy it can show me icons about money and ecommerce. Or when I type menu it should give me hamburger icon.

![Screen Shot 2021-01-25 at 14 57 44](https://user-images.githubusercontent.com/33263846/105703029-b167eb00-5f1d-11eb-85fd-825c1dc7f326.png)

Thanks..

**Comment by gorango** [comment]
Thanks for the suggestion but integrating 3rd party search is not something that I am considering at this time -- for reasons that it doesn't work offline (or works bad with slow internet), it's cumbersome to integrate and is expensive to maintain. You are welcome to make a PR if you believe that it's essential.

Currently, search can be improved by adding keywords and phrases to the component descriptions in Figma.

The examples you gave are good suggestions and I have added those terms to the icons in Figma. They will be live in the next few days.
