### ISSUE TITLE
[docs] Contributing Guide (contributing.md) errors

### ISSUE THREAD

**Issue by 1shevelov** [gorango/glyphs#8]
Errors in Contributing guide:

1) "Code of Conduct" file is missing or the link is invalid. Current link is [https://github.com/gorango/glyphs/blob/main/.github/CODE_OF_CONDUCT.md](https://github.com/gorango/glyphs/blob/main/.github/CODE_OF_CONDUCT.md).

2) There is no "Project Structure" and "Financial Contribution" sections but they are present in the Content section with links.
I would suggest completely remove them until these sections will be made. Or remove just links and add a note like "(will be added later)".

I decided to add second item as a bug after I ended in the situation on a screenshot - Glyphs Github main page with the broken Contributing Guide link in the address bar:
![glyphs_links](https://user-images.githubusercontent.com/30589388/96364866-86fbda00-1145-11eb-9064-b8bd024718d9.png)

Repro script:
1) Go to Glyphs contributing guide: [https://github.com/gorango/glyphs/blob/main/contributing.md](https://github.com/gorango/glyphs/blob/main/contributing.md)
2) Click one of the broken link "Project Structure" or "Financial Contribution".
3) Then click some other link, [Glyphs Github page](https://github.com/gorango/glyphs) in my case.
4) Click "Back" browser button.

The error on a screenshot happens in desktop Firefox browser (81.0.2). Desktop Chrome correctly shows Contributing Guide page. So this is more like a browser problem, but easy to fix on your side.

Thanks for the Glyphs!

**Comment by gorango** [comment]
Thank you for submitting this issue! It was an oversight on my part since I copied some of this content from another repo. I will remove those links for now.
